//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_db1_CONSOLE_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Emp_id { get; set; }
        public string Name { get; set; }
        public decimal salary { get; set; }
        public int dept_id { get; set; }
    }
}
